spring:
  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/crudusers?useSSL=false&serverTimeZone=UTC
     username: root
     password: ''

  jpa:
      properties:
        hibernate:
           ddl-auto: update
           dialect: org.hibernate.dialect.MySQL5Dialect
           generate-ddl: true